# 介绍 {#Introduction .unnumbered}

LI-6400 光合仪自面世以来，在相关的领域得到了广泛的应用。毕竟在植物学领域，专门光合相关的研究或其他研究很多时候都需要光合相关的参数来比较不同处理或者验证某些假设。尽管是一个经典的设备，目前在每年的生长季节使用量也十分巨大（这个作为一个售后的感受是最直观的），但它不可避免的落伍于这个时代，并最终停止生产了，取而代之的是 LI-6800 光合仪。对于这个变化而言，一个很直观的例子可以解释为什么在 LI-6400 仍然能胜任多数光合测量任务的情况下，却难逃被淘汰的命运。这就是手机从功能机向智能机的转变，并不是直板诺基亚不好了，只是时代对手机提出来更高的要求。 LI-6800 的诞生意味着光合仪从功能机时代转向了智能机的时代，无限的可能被创造力出来。

不论仪器怎么转变，他们可能会节省我们很多劳动力，让我们少去操心一些琐碎的问题，但最终的数据处理则是科研工作者核心的工作的主题，时代进步可能会减轻我们的工作量，例如最近这十几年来，大数据的兴起使得我们对数据分析的难度大大降低。新方法新工具不断出现，这对我们是一个好的事情，但同时对我们的学习要求也不断提高，因为不能悲哀的发现分析结果出来，我们却读不懂吧。当然，更多的情况是我们受制于怎么实现某些分析，怎么利用程序能够自动化的处理一些工作，好让我们把精力更多的放在对数据结果的分析和讨论上。

基于此，也基于我个人这几年对相关方面的兴趣，我这里将我所知道关于对光合数据分析相关的内容做一个整理，不管水平如何，我只是期望能给未入门或者初入门尚未找到合适资料的同志们一些参考。我努力保证不出错，但不能保证我所使用的代码是最简单、最合理，最有效率的，当然，这是我的目标，但作为一个有不相关工作的业余人士来讲，这很难，所以老师和同学们（不是我没礼貌，只是年纪在这，可能某些同学的老师是我的同学，我只能这么喊了）口下留情，请多多指正，多多分享。

我对这块工作，目前期望的框架大致为（基于 [使用 R 语言分析 LI-6400 和 LI-6800 光合仪的数据](https://zhujiedong.github.io/photoanalysis/) 得到的一些总结和反馈）：

1.  介绍基本工具安装和初步的使用，这里目前准备先介绍一下 `R`，`Rtools` 及 `Rstudio` 的安装和基本使用，因为作为初学者这是最基本的工具，所谓工欲善其事，必先利其器，掌握了 `Rstudio` 之后再写代码就是事倍功半的效果了，添加这部分内容是因为看到不少人给我截图，都是直接用的 R gui，这个真的很费事的，我就刚学 `R` 的时候用过这种方式，后来一路到 `Rstudio` 成立，就再也没换过写 `R` 代码的工具。

2.  介绍专门的光合作用软件包，因为光合数据处理，特别是一些曲线拟合的部分相对比较麻烦，有一些特有的软件包进行使用，例如 `plantecophys` 等。

3.  数据的准备工作，最基本的数据导入，批量导入和处理。

4.  响应曲线部分与叶片导度部分，这里主要介绍气孔导度相关模型与叶肉导度的计算。

5.  其他统计常用方法。这里准备介绍基本的统计方法。

::: callout-note
## 注意

我对 `tidyverse` 的管道符号并不感冒，而且我又有一定程度的强迫症，不喜欢使用太多依赖，所以代码我基本会尽量使用 `R` base 的语法来进行示例,这样初学者不用安装太多依赖包来运行示例程序，这是个人习惯的问题。
:::
